stages:
- build
- test
#- release

variables:
  IMAGE: aksw/agdistis:latest

build:
  image: maven
  stage: build
  only:
    - docker
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
    - target/*.war

test:
  stage: test
  only:
    - docker
  before_script:
    - apt-get update && apt-get install p7zip-full
  script:
    - wget http://titan.informatik.uni-leipzig.de/rusbeck/agdistis/en/indexdbpedia_en_2014.7z
    - 7z x indexdbpedia_en_2014.7z
    - mvn test

#release:
#  image: docker:latest
#  stage: release
#  services:
#    - docker:dind
#  only:
#    - docker
#  before_script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
#  script:
#    - docker build --pull -t $IMAGE .
#    - docker push $IMAGE
